// Sourced from the mledoze/countries dataset (ISO 3166 + ITU calling codes).
// NANP members (root +1: US, Canada, Caribbean nations) are intentionally collapsed to the
// bare "+1" prefix (no area-code suffix), and Russia/Kazakhstan intentionally share "+7" —
// both are real shared numbering zones, not duplicate/incorrect data.
import type { Language } from '../types/database';

export interface CountryPrefix {
  iso2: string;
  code: string;
  nameFr: string;
  nameEn: string;
  nameAr: string;
}

export const DEFAULT_COUNTRY_ISO2 = 'MA';

export const COUNTRY_PREFIXES: CountryPrefix[] = [
  { iso2: "AF", code: "+93", nameFr: "Afghanistan", nameEn: "Afghanistan", nameAr: "أفغانستان" },
  { iso2: "AX", code: "+35818", nameFr: "Ahvenanmaa", nameEn: "Åland Islands", nameAr: "جزر أولاند" },
  { iso2: "AL", code: "+355", nameFr: "Albanie", nameEn: "Albania", nameAr: "ألبانيا" },
  { iso2: "DZ", code: "+213", nameFr: "Algérie", nameEn: "Algeria", nameAr: "الجزائر" },
  { iso2: "AS", code: "+1", nameFr: "Samoa américaines", nameEn: "American Samoa", nameAr: "ساموا الأمريكية" },
  { iso2: "AD", code: "+376", nameFr: "Andorre", nameEn: "Andorra", nameAr: "أندورا" },
  { iso2: "AO", code: "+244", nameFr: "Angola", nameEn: "Angola", nameAr: "جمهورية أنغولا" },
  { iso2: "AI", code: "+1", nameFr: "Anguilla", nameEn: "Anguilla", nameAr: "أنغويلا" },
  { iso2: "AG", code: "+1", nameFr: "Antigua-et-Barbuda", nameEn: "Antigua and Barbuda", nameAr: "أنتيغوا وباربودا" },
  { iso2: "AR", code: "+54", nameFr: "Argentine", nameEn: "Argentina", nameAr: "الأرجنتين" },
  { iso2: "AM", code: "+374", nameFr: "Arménie", nameEn: "Armenia", nameAr: "أرمينيا" },
  { iso2: "AW", code: "+297", nameFr: "Aruba", nameEn: "Aruba", nameAr: "أروبا" },
  { iso2: "AU", code: "+61", nameFr: "Australie", nameEn: "Australia", nameAr: "أستراليا" },
  { iso2: "AT", code: "+43", nameFr: "Autriche", nameEn: "Austria", nameAr: "النمسا" },
  { iso2: "AZ", code: "+994", nameFr: "Azerbaïdjan", nameEn: "Azerbaijan", nameAr: "أذربيجان" },
  { iso2: "BS", code: "+1", nameFr: "Bahamas", nameEn: "Bahamas", nameAr: "البهاما" },
  { iso2: "BH", code: "+973", nameFr: "Bahreïn", nameEn: "Bahrain", nameAr: "البحرين" },
  { iso2: "BD", code: "+880", nameFr: "Bangladesh", nameEn: "Bangladesh", nameAr: "بنغلاديش" },
  { iso2: "BB", code: "+1", nameFr: "Barbade", nameEn: "Barbados", nameAr: "باربادوس" },
  { iso2: "BY", code: "+375", nameFr: "Biélorussie", nameEn: "Belarus", nameAr: "بيلاروسيا" },
  { iso2: "BE", code: "+32", nameFr: "Belgique", nameEn: "Belgium", nameAr: "بلجيكا" },
  { iso2: "BZ", code: "+501", nameFr: "Belize", nameEn: "Belize", nameAr: "بليز" },
  { iso2: "BJ", code: "+229", nameFr: "Bénin", nameEn: "Benin", nameAr: "بنين" },
  { iso2: "BM", code: "+1", nameFr: "Bermudes", nameEn: "Bermuda", nameAr: "برمودا" },
  { iso2: "BT", code: "+975", nameFr: "Bhoutan", nameEn: "Bhutan", nameAr: "بوتان" },
  { iso2: "BO", code: "+591", nameFr: "Bolivie", nameEn: "Bolivia", nameAr: "بوليفيا" },
  { iso2: "BA", code: "+387", nameFr: "Bosnie-Herzégovine", nameEn: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك" },
  { iso2: "BW", code: "+267", nameFr: "Botswana", nameEn: "Botswana", nameAr: "بوتسوانا" },
  { iso2: "BR", code: "+55", nameFr: "Brésil", nameEn: "Brazil", nameAr: "البرازيل" },
  { iso2: "IO", code: "+246", nameFr: "Territoire britannique de l'océan Indien", nameEn: "British Indian Ocean Territory", nameAr: "إقليم المحيط الهندي البريطاني" },
  { iso2: "VG", code: "+1", nameFr: "Îles Vierges britanniques", nameEn: "British Virgin Islands", nameAr: "جزر العذراء" },
  { iso2: "BN", code: "+673", nameFr: "Brunei", nameEn: "Brunei", nameAr: "بروناي" },
  { iso2: "BG", code: "+359", nameFr: "Bulgarie", nameEn: "Bulgaria", nameAr: "بلغاريا" },
  { iso2: "BF", code: "+226", nameFr: "Burkina Faso", nameEn: "Burkina Faso", nameAr: "بوركينا فاسو" },
  { iso2: "BI", code: "+257", nameFr: "Burundi", nameEn: "Burundi", nameAr: "بوروندي" },
  { iso2: "KH", code: "+855", nameFr: "Cambodge", nameEn: "Cambodia", nameAr: "كمبوديا" },
  { iso2: "CM", code: "+237", nameFr: "Cameroun", nameEn: "Cameroon", nameAr: "الكاميرون" },
  { iso2: "CA", code: "+1", nameFr: "Canada", nameEn: "Canada", nameAr: "كندا" },
  { iso2: "CV", code: "+238", nameFr: "Îles du Cap-Vert", nameEn: "Cape Verde", nameAr: "كابو فيردي" },
  { iso2: "BQ", code: "+599", nameFr: "Pays-Bas caribéens", nameEn: "Caribbean Netherlands", nameAr: "الجزر الكاريبية الهولندية" },
  { iso2: "KY", code: "+1", nameFr: "Îles Caïmans", nameEn: "Cayman Islands", nameAr: "جزر كايمان" },
  { iso2: "CF", code: "+236", nameFr: "République centrafricaine", nameEn: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى" },
  { iso2: "TD", code: "+235", nameFr: "Tchad", nameEn: "Chad", nameAr: "تشاد" },
  { iso2: "CL", code: "+56", nameFr: "Chili", nameEn: "Chile", nameAr: "تشيلي" },
  { iso2: "CN", code: "+86", nameFr: "Chine", nameEn: "China", nameAr: "الصين" },
  { iso2: "CX", code: "+61", nameFr: "Île Christmas", nameEn: "Christmas Island", nameAr: "جزيرة كريسماس" },
  { iso2: "CC", code: "+61", nameFr: "Îles Cocos", nameEn: "Cocos (Keeling) Islands", nameAr: "جزر كوكوس" },
  { iso2: "CO", code: "+57", nameFr: "Colombie", nameEn: "Colombia", nameAr: "كولومبيا" },
  { iso2: "KM", code: "+269", nameFr: "Comores", nameEn: "Comoros", nameAr: "جزر القمر" },
  { iso2: "CG", code: "+242", nameFr: "Congo", nameEn: "Congo", nameAr: "جمهورية الكونغو" },
  { iso2: "CK", code: "+682", nameFr: "Îles Cook", nameEn: "Cook Islands", nameAr: "جزر كوك" },
  { iso2: "CR", code: "+506", nameFr: "Costa Rica", nameEn: "Costa Rica", nameAr: "كوستاريكا" },
  { iso2: "HR", code: "+385", nameFr: "Croatie", nameEn: "Croatia", nameAr: "كرواتيا" },
  { iso2: "CU", code: "+53", nameFr: "Cuba", nameEn: "Cuba", nameAr: "كوبا" },
  { iso2: "CW", code: "+599", nameFr: "Curaçao", nameEn: "Curaçao", nameAr: "كوراساو" },
  { iso2: "CY", code: "+357", nameFr: "Chypre", nameEn: "Cyprus", nameAr: "قبرص" },
  { iso2: "CZ", code: "+420", nameFr: "Tchéquie", nameEn: "Czechia", nameAr: "التشيك" },
  { iso2: "DK", code: "+45", nameFr: "Danemark", nameEn: "Denmark", nameAr: "الدنمارك" },
  { iso2: "DJ", code: "+253", nameFr: "Djibouti", nameEn: "Djibouti", nameAr: "جيبوتي" },
  { iso2: "DM", code: "+1", nameFr: "Dominique", nameEn: "Dominica", nameAr: "دومينيكا" },
  { iso2: "DO", code: "+1", nameFr: "République dominicaine", nameEn: "Dominican Republic", nameAr: "جمهورية الدومينيكان" },
  { iso2: "CD", code: "+243", nameFr: "Congo (Rép. dém.)", nameEn: "DR Congo", nameAr: "الكونغو" },
  { iso2: "EC", code: "+593", nameFr: "Équateur", nameEn: "Ecuador", nameAr: "الإكوادور" },
  { iso2: "EG", code: "+20", nameFr: "Égypte", nameEn: "Egypt", nameAr: "مصر" },
  { iso2: "SV", code: "+503", nameFr: "Salvador", nameEn: "El Salvador", nameAr: "السلفادور" },
  { iso2: "GQ", code: "+240", nameFr: "Guinée équatoriale", nameEn: "Equatorial Guinea", nameAr: "غينيا الاستوائية" },
  { iso2: "ER", code: "+291", nameFr: "Érythrée", nameEn: "Eritrea", nameAr: "إريتريا" },
  { iso2: "EE", code: "+372", nameFr: "Estonie", nameEn: "Estonia", nameAr: "إستونيا" },
  { iso2: "SZ", code: "+268", nameFr: "Eswatini", nameEn: "Eswatini", nameAr: "إسواتيني" },
  { iso2: "ET", code: "+251", nameFr: "Éthiopie", nameEn: "Ethiopia", nameAr: "إثيوبيا" },
  { iso2: "FK", code: "+500", nameFr: "Îles Malouines", nameEn: "Falkland Islands", nameAr: "جزر فوكلاند" },
  { iso2: "FO", code: "+298", nameFr: "Îles Féroé", nameEn: "Faroe Islands", nameAr: "جزر فارو" },
  { iso2: "FJ", code: "+679", nameFr: "Fidji", nameEn: "Fiji", nameAr: "فيجي" },
  { iso2: "FI", code: "+358", nameFr: "Finlande", nameEn: "Finland", nameAr: "فنلندا" },
  { iso2: "FR", code: "+33", nameFr: "France", nameEn: "France", nameAr: "فرنسا" },
  { iso2: "GF", code: "+594", nameFr: "Guyane", nameEn: "French Guiana", nameAr: "غويانا" },
  { iso2: "PF", code: "+689", nameFr: "Polynésie française", nameEn: "French Polynesia", nameAr: "بولينزيا الفرنسية" },
  { iso2: "GA", code: "+241", nameFr: "Gabon", nameEn: "Gabon", nameAr: "الغابون" },
  { iso2: "GM", code: "+220", nameFr: "Gambie", nameEn: "Gambia", nameAr: "غامبيا" },
  { iso2: "GE", code: "+995", nameFr: "Géorgie", nameEn: "Georgia", nameAr: "جورجيا" },
  { iso2: "DE", code: "+49", nameFr: "Allemagne", nameEn: "Germany", nameAr: "ألمانيا" },
  { iso2: "GH", code: "+233", nameFr: "Ghana", nameEn: "Ghana", nameAr: "غانا" },
  { iso2: "GI", code: "+350", nameFr: "Gibraltar", nameEn: "Gibraltar", nameAr: "جبل طارق" },
  { iso2: "GR", code: "+30", nameFr: "Grèce", nameEn: "Greece", nameAr: "اليونان" },
  { iso2: "GL", code: "+299", nameFr: "Groenland", nameEn: "Greenland", nameAr: "جرينلاند" },
  { iso2: "GD", code: "+1", nameFr: "Grenade", nameEn: "Grenada", nameAr: "غرينادا" },
  { iso2: "GP", code: "+590", nameFr: "Guadeloupe", nameEn: "Guadeloupe", nameAr: "غوادلوب" },
  { iso2: "GU", code: "+1", nameFr: "Guam", nameEn: "Guam", nameAr: "غوام" },
  { iso2: "GT", code: "+502", nameFr: "Guatemala", nameEn: "Guatemala", nameAr: "غواتيمالا" },
  { iso2: "GG", code: "+44", nameFr: "Guernesey", nameEn: "Guernsey", nameAr: "غيرنزي" },
  { iso2: "GN", code: "+224", nameFr: "Guinée", nameEn: "Guinea", nameAr: "غينيا" },
  { iso2: "GW", code: "+245", nameFr: "Guinée-Bissau", nameEn: "Guinea-Bissau", nameAr: "غينيا بيساو" },
  { iso2: "GY", code: "+592", nameFr: "Guyana", nameEn: "Guyana", nameAr: "غيانا" },
  { iso2: "HT", code: "+509", nameFr: "Haïti", nameEn: "Haiti", nameAr: "هايتي" },
  { iso2: "HN", code: "+504", nameFr: "Honduras", nameEn: "Honduras", nameAr: "هندوراس" },
  { iso2: "HK", code: "+852", nameFr: "Hong Kong", nameEn: "Hong Kong", nameAr: "هونغ كونغ" },
  { iso2: "HU", code: "+36", nameFr: "Hongrie", nameEn: "Hungary", nameAr: "المجر" },
  { iso2: "IS", code: "+354", nameFr: "Islande", nameEn: "Iceland", nameAr: "آيسلندا" },
  { iso2: "IN", code: "+91", nameFr: "Inde", nameEn: "India", nameAr: "الهند" },
  { iso2: "ID", code: "+62", nameFr: "Indonésie", nameEn: "Indonesia", nameAr: "إندونيسيا" },
  { iso2: "IR", code: "+98", nameFr: "Iran", nameEn: "Iran", nameAr: "إيران" },
  { iso2: "IQ", code: "+964", nameFr: "Irak", nameEn: "Iraq", nameAr: "العراق" },
  { iso2: "IE", code: "+353", nameFr: "Irlande", nameEn: "Ireland", nameAr: "أيرلندا" },
  { iso2: "IM", code: "+44", nameFr: "Île de Man", nameEn: "Isle of Man", nameAr: "جزيرة مان" },
  { iso2: "IL", code: "+972", nameFr: "Israël", nameEn: "Israel", nameAr: "إسرائيل" },
  { iso2: "IT", code: "+39", nameFr: "Italie", nameEn: "Italy", nameAr: "إيطاليا" },
  { iso2: "CI", code: "+225", nameFr: "Côte d'Ivoire", nameEn: "Ivory Coast", nameAr: "ساحل العاج" },
  { iso2: "JM", code: "+1", nameFr: "Jamaïque", nameEn: "Jamaica", nameAr: "جامايكا" },
  { iso2: "JP", code: "+81", nameFr: "Japon", nameEn: "Japan", nameAr: "اليابان" },
  { iso2: "JE", code: "+44", nameFr: "Jersey", nameEn: "Jersey", nameAr: "جيرزي" },
  { iso2: "JO", code: "+962", nameFr: "Jordanie", nameEn: "Jordan", nameAr: "الأردن" },
  { iso2: "KZ", code: "+7", nameFr: "Kazakhstan", nameEn: "Kazakhstan", nameAr: "كازاخستان" },
  { iso2: "KE", code: "+254", nameFr: "Kenya", nameEn: "Kenya", nameAr: "كينيا" },
  { iso2: "KI", code: "+686", nameFr: "Kiribati", nameEn: "Kiribati", nameAr: "كيريباتي" },
  { iso2: "XK", code: "+383", nameFr: "Kosovo", nameEn: "Kosovo", nameAr: "كوسوفو" },
  { iso2: "KW", code: "+965", nameFr: "Koweït", nameEn: "Kuwait", nameAr: "الكويت" },
  { iso2: "KG", code: "+996", nameFr: "Kirghizistan", nameEn: "Kyrgyzstan", nameAr: "قيرغيزستان" },
  { iso2: "LA", code: "+856", nameFr: "Laos", nameEn: "Laos", nameAr: "لاوس" },
  { iso2: "LV", code: "+371", nameFr: "Lettonie", nameEn: "Latvia", nameAr: "لاتفيا" },
  { iso2: "LB", code: "+961", nameFr: "Liban", nameEn: "Lebanon", nameAr: "لبنان" },
  { iso2: "LS", code: "+266", nameFr: "Lesotho", nameEn: "Lesotho", nameAr: "ليسوتو" },
  { iso2: "LR", code: "+231", nameFr: "Liberia", nameEn: "Liberia", nameAr: "ليبيريا" },
  { iso2: "LY", code: "+218", nameFr: "Libye", nameEn: "Libya", nameAr: "ليبيا" },
  { iso2: "LI", code: "+423", nameFr: "Liechtenstein", nameEn: "Liechtenstein", nameAr: "ليختنشتاين" },
  { iso2: "LT", code: "+370", nameFr: "Lituanie", nameEn: "Lithuania", nameAr: "ليتوانيا" },
  { iso2: "LU", code: "+352", nameFr: "Luxembourg", nameEn: "Luxembourg", nameAr: "لوكسمبورغ" },
  { iso2: "MO", code: "+853", nameFr: "Macao", nameEn: "Macau", nameAr: "ماكاو" },
  { iso2: "MG", code: "+261", nameFr: "Madagascar", nameEn: "Madagascar", nameAr: "مدغشقر" },
  { iso2: "MW", code: "+265", nameFr: "Malawi", nameEn: "Malawi", nameAr: "مالاوي" },
  { iso2: "MY", code: "+60", nameFr: "Malaisie", nameEn: "Malaysia", nameAr: "ماليزيا" },
  { iso2: "MV", code: "+960", nameFr: "Maldives", nameEn: "Maldives", nameAr: "المالديف" },
  { iso2: "ML", code: "+223", nameFr: "Mali", nameEn: "Mali", nameAr: "مالي" },
  { iso2: "MT", code: "+356", nameFr: "Malte", nameEn: "Malta", nameAr: "مالطا" },
  { iso2: "MH", code: "+692", nameFr: "Îles Marshall", nameEn: "Marshall Islands", nameAr: "جزر مارشال" },
  { iso2: "MQ", code: "+596", nameFr: "Martinique", nameEn: "Martinique", nameAr: "مارتينيك" },
  { iso2: "MR", code: "+222", nameFr: "Mauritanie", nameEn: "Mauritania", nameAr: "موريتانيا" },
  { iso2: "MU", code: "+230", nameFr: "Île Maurice", nameEn: "Mauritius", nameAr: "موريشيوس" },
  { iso2: "YT", code: "+262", nameFr: "Mayotte", nameEn: "Mayotte", nameAr: "مايوت" },
  { iso2: "MX", code: "+52", nameFr: "Mexique", nameEn: "Mexico", nameAr: "المسكيك" },
  { iso2: "FM", code: "+691", nameFr: "Micronésie", nameEn: "Micronesia", nameAr: "ميكرونيسيا" },
  { iso2: "MD", code: "+373", nameFr: "Moldavie", nameEn: "Moldova", nameAr: "مولدوڤا" },
  { iso2: "MC", code: "+377", nameFr: "Monaco", nameEn: "Monaco", nameAr: "موناكو" },
  { iso2: "MN", code: "+976", nameFr: "Mongolie", nameEn: "Mongolia", nameAr: "منغوليا" },
  { iso2: "ME", code: "+382", nameFr: "Monténégro", nameEn: "Montenegro", nameAr: "الجبل الاسود" },
  { iso2: "MS", code: "+1", nameFr: "Montserrat", nameEn: "Montserrat", nameAr: "مونتسرات" },
  { iso2: "MA", code: "+212", nameFr: "Maroc", nameEn: "Morocco", nameAr: "المغرب" },
  { iso2: "MZ", code: "+258", nameFr: "Mozambique", nameEn: "Mozambique", nameAr: "موزمبيق" },
  { iso2: "MM", code: "+95", nameFr: "Birmanie", nameEn: "Myanmar", nameAr: "ميانمار" },
  { iso2: "NA", code: "+264", nameFr: "Namibie", nameEn: "Namibia", nameAr: "ناميبيا" },
  { iso2: "NR", code: "+674", nameFr: "Nauru", nameEn: "Nauru", nameAr: "ناورو" },
  { iso2: "NP", code: "+977", nameFr: "Népal", nameEn: "Nepal", nameAr: "نيبال" },
  { iso2: "NL", code: "+31", nameFr: "Pays-Bas", nameEn: "Netherlands", nameAr: "هولندا" },
  { iso2: "NC", code: "+687", nameFr: "Nouvelle-Calédonie", nameEn: "New Caledonia", nameAr: "كاليدونيا الجديدة" },
  { iso2: "NZ", code: "+64", nameFr: "Nouvelle-Zélande", nameEn: "New Zealand", nameAr: "نيوزيلندا" },
  { iso2: "NI", code: "+505", nameFr: "Nicaragua", nameEn: "Nicaragua", nameAr: "نيكاراغوا" },
  { iso2: "NE", code: "+227", nameFr: "Niger", nameEn: "Niger", nameAr: "النيجر" },
  { iso2: "NG", code: "+234", nameFr: "Nigéria", nameEn: "Nigeria", nameAr: "نيجيريا" },
  { iso2: "NU", code: "+683", nameFr: "Niue", nameEn: "Niue", nameAr: "نييوي" },
  { iso2: "NF", code: "+672", nameFr: "Île Norfolk", nameEn: "Norfolk Island", nameAr: "جزيرة نورفولك" },
  { iso2: "KP", code: "+850", nameFr: "Corée du Nord", nameEn: "North Korea", nameAr: "كوريا الشمالية" },
  { iso2: "MK", code: "+389", nameFr: "Macédoine du Nord", nameEn: "North Macedonia", nameAr: "شمال مقدونيا" },
  { iso2: "MP", code: "+1", nameFr: "Îles Mariannes du Nord", nameEn: "Northern Mariana Islands", nameAr: "جزر ماريانا الشمالية" },
  { iso2: "NO", code: "+47", nameFr: "Norvège", nameEn: "Norway", nameAr: "النرويج" },
  { iso2: "OM", code: "+968", nameFr: "Oman", nameEn: "Oman", nameAr: "عمان" },
  { iso2: "PK", code: "+92", nameFr: "Pakistan", nameEn: "Pakistan", nameAr: "باكستان" },
  { iso2: "PW", code: "+680", nameFr: "Palaos (Palau)", nameEn: "Palau", nameAr: "بالاو" },
  { iso2: "PS", code: "+970", nameFr: "Palestine", nameEn: "Palestine", nameAr: "فلسطين" },
  { iso2: "PA", code: "+507", nameFr: "Panama", nameEn: "Panama", nameAr: "بنما" },
  { iso2: "PG", code: "+675", nameFr: "Papouasie-Nouvelle-Guinée", nameEn: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة" },
  { iso2: "PY", code: "+595", nameFr: "Paraguay", nameEn: "Paraguay", nameAr: "باراغواي" },
  { iso2: "PE", code: "+51", nameFr: "Pérou", nameEn: "Peru", nameAr: "بيرو" },
  { iso2: "PH", code: "+63", nameFr: "Philippines", nameEn: "Philippines", nameAr: "الفلبين" },
  { iso2: "PN", code: "+64", nameFr: "Îles Pitcairn", nameEn: "Pitcairn Islands", nameAr: "جزر بيتكيرن" },
  { iso2: "PL", code: "+48", nameFr: "Pologne", nameEn: "Poland", nameAr: "بولندا" },
  { iso2: "PT", code: "+351", nameFr: "Portugal", nameEn: "Portugal", nameAr: "البرتغال" },
  { iso2: "PR", code: "+1", nameFr: "Porto Rico", nameEn: "Puerto Rico", nameAr: "بويرتوريكو" },
  { iso2: "QA", code: "+974", nameFr: "Qatar", nameEn: "Qatar", nameAr: "قطر" },
  { iso2: "RE", code: "+262", nameFr: "Réunion", nameEn: "Réunion", nameAr: "لا ريونيون" },
  { iso2: "RO", code: "+40", nameFr: "Roumanie", nameEn: "Romania", nameAr: "رومانيا" },
  { iso2: "RU", code: "+7", nameFr: "Russie", nameEn: "Russia", nameAr: "روسيا" },
  { iso2: "RW", code: "+250", nameFr: "Rwanda", nameEn: "Rwanda", nameAr: "رواندا" },
  { iso2: "BL", code: "+590", nameFr: "Saint-Barthélemy", nameEn: "Saint Barthélemy", nameAr: "سان بارتليمي" },
  { iso2: "SH", code: "+290", nameFr: "Sainte-Hélène, Ascension et Tristan da Cunha", nameEn: "Saint Helena, Ascension and Tristan da Cunha", nameAr: "سانت هيلينا وأسينشين وتريستان دا كونا" },
  { iso2: "KN", code: "+1", nameFr: "Saint-Christophe-et-Niévès", nameEn: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس" },
  { iso2: "LC", code: "+1", nameFr: "Sainte-Lucie", nameEn: "Saint Lucia", nameAr: "سانت لوسيا" },
  { iso2: "MF", code: "+590", nameFr: "Saint-Martin", nameEn: "Saint Martin", nameAr: "سانت مارتن" },
  { iso2: "PM", code: "+508", nameFr: "Saint-Pierre-et-Miquelon", nameEn: "Saint Pierre and Miquelon", nameAr: "سان بيير وميكلون" },
  { iso2: "VC", code: "+1", nameFr: "Saint-Vincent-et-les-Grenadines", nameEn: "Saint Vincent and the Grenadines", nameAr: "سانت فينسنت والغرينادين" },
  { iso2: "WS", code: "+685", nameFr: "Samoa", nameEn: "Samoa", nameAr: "ساموا" },
  { iso2: "SM", code: "+378", nameFr: "Saint-Marin", nameEn: "San Marino", nameAr: "سان مارينو" },
  { iso2: "ST", code: "+239", nameFr: "São Tomé et Príncipe", nameEn: "São Tomé and Príncipe", nameAr: "ساو تومي وبرينسيب" },
  { iso2: "SA", code: "+966", nameFr: "Arabie Saoudite", nameEn: "Saudi Arabia", nameAr: "السعودية" },
  { iso2: "SN", code: "+221", nameFr: "Sénégal", nameEn: "Senegal", nameAr: "السنغال" },
  { iso2: "RS", code: "+381", nameFr: "Serbie", nameEn: "Serbia", nameAr: "صيربيا" },
  { iso2: "SC", code: "+248", nameFr: "Seychelles", nameEn: "Seychelles", nameAr: "سيشل" },
  { iso2: "SL", code: "+232", nameFr: "Sierra Leone", nameEn: "Sierra Leone", nameAr: "سيراليون" },
  { iso2: "SG", code: "+65", nameFr: "Singapour", nameEn: "Singapore", nameAr: "سنغافورة" },
  { iso2: "SX", code: "+1", nameFr: "Saint-Martin", nameEn: "Sint Maarten", nameAr: "سينت مارتن" },
  { iso2: "SK", code: "+421", nameFr: "Slovaquie", nameEn: "Slovakia", nameAr: "سلوفاكيا" },
  { iso2: "SI", code: "+386", nameFr: "Slovénie", nameEn: "Slovenia", nameAr: "سلوفينيا" },
  { iso2: "SB", code: "+677", nameFr: "Îles Salomon", nameEn: "Solomon Islands", nameAr: "جزر سليمان" },
  { iso2: "SO", code: "+252", nameFr: "Somalie", nameEn: "Somalia", nameAr: "الصومال" },
  { iso2: "ZA", code: "+27", nameFr: "Afrique du Sud", nameEn: "South Africa", nameAr: "جنوب أفريقيا" },
  { iso2: "KR", code: "+82", nameFr: "Corée du Sud", nameEn: "South Korea", nameAr: "كوريا الجنوبية" },
  { iso2: "SS", code: "+211", nameFr: "Soudan du Sud", nameEn: "South Sudan", nameAr: "جنوب السودان" },
  { iso2: "ES", code: "+34", nameFr: "Espagne", nameEn: "Spain", nameAr: "إسبانيا" },
  { iso2: "LK", code: "+94", nameFr: "Sri Lanka", nameEn: "Sri Lanka", nameAr: "سريلانكا" },
  { iso2: "SD", code: "+249", nameFr: "Soudan", nameEn: "Sudan", nameAr: "السودان" },
  { iso2: "SR", code: "+597", nameFr: "Surinam", nameEn: "Suriname", nameAr: "سورينام" },
  { iso2: "SJ", code: "+4779", nameFr: "Svalbard et Jan Mayen", nameEn: "Svalbard and Jan Mayen", nameAr: "سفالبارد ويان ماين" },
  { iso2: "SE", code: "+46", nameFr: "Suède", nameEn: "Sweden", nameAr: "السويد" },
  { iso2: "CH", code: "+41", nameFr: "Suisse", nameEn: "Switzerland", nameAr: "سويسرا" },
  { iso2: "SY", code: "+963", nameFr: "Syrie", nameEn: "Syria", nameAr: "سوريا" },
  { iso2: "TW", code: "+886", nameFr: "Taïwan", nameEn: "Taiwan", nameAr: "تايوان" },
  { iso2: "TJ", code: "+992", nameFr: "Tadjikistan", nameEn: "Tajikistan", nameAr: "طاجيكستان" },
  { iso2: "TZ", code: "+255", nameFr: "Tanzanie", nameEn: "Tanzania", nameAr: "تنزانيا" },
  { iso2: "TH", code: "+66", nameFr: "Thaïlande", nameEn: "Thailand", nameAr: "تايلند" },
  { iso2: "TL", code: "+670", nameFr: "Timor oriental", nameEn: "Timor-Leste", nameAr: "تيمور الشرقية" },
  { iso2: "TG", code: "+228", nameFr: "Togo", nameEn: "Togo", nameAr: "توغو" },
  { iso2: "TK", code: "+690", nameFr: "Tokelau", nameEn: "Tokelau", nameAr: "توكيلاو" },
  { iso2: "TO", code: "+676", nameFr: "Tonga", nameEn: "Tonga", nameAr: "تونغا" },
  { iso2: "TT", code: "+1", nameFr: "Trinité-et-Tobago", nameEn: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو" },
  { iso2: "TN", code: "+216", nameFr: "Tunisie", nameEn: "Tunisia", nameAr: "تونس" },
  { iso2: "TR", code: "+90", nameFr: "Turquie", nameEn: "Türkiye", nameAr: "تركيا" },
  { iso2: "TM", code: "+993", nameFr: "Turkménistan", nameEn: "Turkmenistan", nameAr: "تركمانستان" },
  { iso2: "TC", code: "+1", nameFr: "Îles Turques-et-Caïques", nameEn: "Turks and Caicos Islands", nameAr: "جزر توركس وكايكوس" },
  { iso2: "TV", code: "+688", nameFr: "Tuvalu", nameEn: "Tuvalu", nameAr: "توفالو" },
  { iso2: "UG", code: "+256", nameFr: "Ouganda", nameEn: "Uganda", nameAr: "أوغندا" },
  { iso2: "UA", code: "+380", nameFr: "Ukraine", nameEn: "Ukraine", nameAr: "أوكرانيا" },
  { iso2: "AE", code: "+971", nameFr: "Émirats arabes unis", nameEn: "United Arab Emirates", nameAr: "الإمارات" },
  { iso2: "GB", code: "+44", nameFr: "Royaume-Uni", nameEn: "United Kingdom", nameAr: "المملكة المتحدة" },
  { iso2: "US", code: "+1", nameFr: "États-Unis", nameEn: "United States", nameAr: "الولايات المتحدة" },
  { iso2: "VI", code: "+1", nameFr: "Îles Vierges des États-Unis", nameEn: "United States Virgin Islands", nameAr: "جزر العذراء الامريكية" },
  { iso2: "UY", code: "+598", nameFr: "Uruguay", nameEn: "Uruguay", nameAr: "الأوروغواي" },
  { iso2: "UZ", code: "+998", nameFr: "Ouzbékistan", nameEn: "Uzbekistan", nameAr: "أوزباكستان" },
  { iso2: "VU", code: "+678", nameFr: "Vanuatu", nameEn: "Vanuatu", nameAr: "فانواتو" },
  { iso2: "VA", code: "+3906698", nameFr: "Cité du Vatican", nameEn: "Vatican City", nameAr: "مدينة الفاتيكان" },
  { iso2: "VE", code: "+58", nameFr: "Venezuela", nameEn: "Venezuela", nameAr: "فنزويلا" },
  { iso2: "VN", code: "+84", nameFr: "Viêt Nam", nameEn: "Vietnam", nameAr: "فيتنام" },
  { iso2: "WF", code: "+681", nameFr: "Wallis-et-Futuna", nameEn: "Wallis and Futuna", nameAr: "واليس وفوتونا" },
  { iso2: "EH", code: "+2125288", nameFr: "Sahara Occidental", nameEn: "Western Sahara", nameAr: "الصحراء الغربية" },
  { iso2: "YE", code: "+967", nameFr: "Yémen", nameEn: "Yemen", nameAr: "اليمن" },
  { iso2: "ZM", code: "+260", nameFr: "Zambie", nameEn: "Zambia", nameAr: "زامبيا" },
  { iso2: "ZW", code: "+263", nameFr: "Zimbabwe", nameEn: "Zimbabwe", nameAr: "زيمبابوي" },
];

export function getCountryByIso2(iso2: string): CountryPrefix | undefined {
  return COUNTRY_PREFIXES.find((c) => c.iso2 === iso2);
}

export function getCountryName(country: CountryPrefix, lang: Language): string {
  if (lang === 'ar') return country.nameAr;
  if (lang === 'en') return country.nameEn;
  return country.nameFr;
}

export function getSortedCountryPrefixes(lang: Language): CountryPrefix[] {
  return [...COUNTRY_PREFIXES].sort((a, b) =>
    getCountryName(a, lang).localeCompare(getCountryName(b, lang), lang === 'ar' ? 'ar' : lang)
  );
}
