import type { LocationItem, Vehicle, Testimonial, SiteSettings, Reservation, CorporateQuoteRequest } from '../types/database';

import heroImg from '../assets/images/hero_soubaicar_morocco_1790271578816.jpg';
import agencyLaayouneImg from '../assets/images/agency_laayoune_facade_1790271591267.jpg';
import agencyDakhlaImg from '../assets/images/agency_dakhla_lagoon_1790271602448.jpg';
import agencyBoujdourImg from '../assets/images/agency_boujdour_coast_1790271613020.jpg';
import vehicleSuvImg from '../assets/images/vehicle_suv_showcase_1790271623037.jpg';

export const ASSET_IMAGES = {
  hero: heroImg,
  agencyLaayoune: agencyLaayouneImg,
  agencyDakhla: agencyDakhlaImg,
  agencyBoujdour: agencyBoujdourImg,
  vehicleSuv: vehicleSuvImg,
};

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'loc-1',
    name: 'Laâyoune',
    slug: 'laayoune',
    address: 'Boulevard Mekka / Avenue de l’Islam, Laâyoune 70000, Maroc',
    phone: '+212 661 140 000',
    whatsapp: '+212 661 140 000',
    email: 'contact@soubaicar.ma',
    description_fr: 'Agence principale SOUBAICAR à Laâyoune. Mise à disposition rapide en ville et livraison immédiate à l’Aéroport Laâyoune Hassan 1er.',
    description_en: 'Main SOUBAICAR branch in Laâyoune. Fast city pickup and express delivery to Laâyoune Hassan 1st International Airport.',
    description_ar: 'وكالة سوبيكار الرئيسية في العيون. تسليم فوري داخل المدينة وفي مطار العيون الحسن الأول.',
    image_url: agencyLaayouneImg,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'loc-2',
    name: 'Boujdour',
    slug: 'boujdour',
    address: 'Boulevard Hassan II, Centre-Ville, Boujdour 71000, Maroc',
    phone: '+212 661 140 000',
    whatsapp: '+212 661 140 000',
    email: 'contact@soubaicar.ma',
    description_fr: 'Agence SOUBAICAR Boujdour. Service de proximité pour vos trajets professionnels et voyages le long de la côte atlantique.',
    description_en: 'SOUBAICAR Boujdour branch. Reliable local service for business trips and coastal travel along the Atlantic corridor.',
    description_ar: 'وكالة سوبيكار في بوجدور. خدمة متميزة لرحلاتكم المهنية والشخصية على طول الساحل الأطلسي.',
    image_url: agencyBoujdourImg,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'loc-3',
    name: 'Dakhla',
    slug: 'dakhla',
    address: 'Boulevard Mohammed V & Accueil Aéroport Dakhla, Dakhla 73000, Maroc',
    phone: '+212 661 140 000',
    whatsapp: '+212 661 140 000',
    email: 'contact@soubaicar.ma',
    description_fr: 'Agence SOUBAICAR Dakhla. Flotte adaptée pour la lagune, les spots de kitesurf, le désert et livraison directe à l’Aéroport de Dakhla.',
    description_en: 'SOUBAICAR Dakhla branch. Premium vehicles tailored for lagoon exploration, desert excursions, and direct Dakhla Airport delivery.',
    description_ar: 'وكالة سوبيكار في الداخلة. أسطول مناسب للبحيرة، مناطق الرياضات البحرية، الصحراء مع التوصيل لمطار الداخلة.',
    image_url: agencyDakhlaImg,
    active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    name: 'Dacia Duster 4x4 Prestige',
    slug: 'dacia-duster-4x4-prestige',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: 450,
    description_fr: 'Le véhicule idéal pour parcourir le Sud du Maroc, entre côtes atlantiques et pistes sahariennes. Robuste, économique et surélevé.',
    description_en: 'The ideal SUV for Southern Morocco, handling coastal highways and desert tracks with ease. Robust, spacious, and fuel efficient.',
    description_ar: 'السيارة المثالية لاكتشاف جنوب المغرب بين السواحل الأطلسية والمسارات الصحراوية. قوية، اقتصادية ومريحة.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-2',
    name: 'Dacia Sandero Stepway',
    slug: 'dacia-sandero-stepway',
    category: 'Compacte',
    fuel: 'Diesel',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: 300,
    description_fr: 'Compacte surélevée moderne, polyvalente en ville comme sur route nationale. Confort optimal, climatisation et faible consommation.',
    description_en: 'Modern crossover compact, versatile for city driving and regional highways. High comfort, air conditioning, and low fuel consumption.',
    description_ar: 'سيارة مدمجة مرتفعة وعصرية، مثالية للمدينة والمسافات الطويلة مع استهلاك اقتصادي للوقود.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-3',
    name: 'Renault Clio 5',
    slug: 'renault-clio-5',
    category: 'Citadine',
    fuel: 'Diesel',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: 280,
    description_fr: 'Citadine dynamique et raffinée, idéale pour vos déplacements urbains et courts séjours à Laâyoune, Boujdour ou Dakhla.',
    description_en: 'Refined dynamic city car, perfect for urban travel and short stays across Laâyoune, Boujdour, and Dakhla.',
    description_ar: 'سيارة مدينة أنيقة وديناميكية، مثالية للتنقل اليومي والرحلات القصيرة في العيون وبوجدور والداخلة.',
    image_url: vehicleSuvImg,
    featured: false,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-4',
    name: 'Hyundai Tucson Automatique',
    slug: 'hyundai-tucson-automatique',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Automatique',
    seats: 5,
    air_conditioning: true,
    price: 650,
    description_fr: 'SUV haut de gamme alliant confort premium, boîte automatique souple et technologie de pointe pour vos longs trajets dans le Sud.',
    description_en: 'High-end premium SUV combining smooth automatic transmission and cutting-edge tech for long journeys in Southern Morocco.',
    description_ar: 'سيارة دفع رباعي فخمة تجمع بين الراحة القصوى وناقل الحركة الأوتوماتيكي والتقنيات الحديثة.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-5',
    name: 'Toyota Land Cruiser Prado TXL',
    slug: 'toyota-land-cruiser-prado-txl',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Automatique',
    seats: 7,
    air_conditioning: true,
    price: null, // Sur devis / On request
    description_fr: 'Vrai 4x4 de référence pour les expéditions de prestige, délégations professionnelles et circuits désertiques à Dakhla et Laâyoune.',
    description_en: 'The benchmark 4WD for VIP delegations, desert expeditions, and supreme travel in Dakhla and Laâyoune. Available on custom quote.',
    description_ar: 'المرجع الأول لسيارات الدفع الرباعي للبعثات والرحلات الصحراوية الفاخرة في الداخلة والعيون.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-6',
    name: 'Peugeot 208 Allure',
    slug: 'peugeot-208-allure',
    category: 'Citadine',
    fuel: 'Diesel',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: 280,
    description_fr: 'Design audacieux, habitacle moderne i-Cockpit et maniabilité exemplaire pour découvrir la ville en toute sérénité.',
    description_en: 'Bold design, modern cockpit, and agile handling for cruising through city centers with complete peace of mind.',
    description_ar: 'تصميم جريء ومقصورة قيادة متطورة وسهولة قيادة لا مثيل لها للتنقل بكل أريحية.',
    image_url: vehicleSuvImg,
    featured: false,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-101',
    customer_name: 'Karim Bennani',
    email: 'karim.bennani@example.com',
    phone: '+212 661 234 567',
    country: 'Maroc',
    vehicle_id: 'veh-1',
    vehicle_name: 'Dacia Duster 4x4 Prestige',
    location_id: 'loc-3',
    location_name: 'Dakhla',
    pickup_date: '2026-10-05',
    return_date: '2026-10-12',
    message: 'Arrivée vol AT1422 à Dakhla à 14h30. Besoin de livraison à l’aéroport.',
    status: 'new',
    language: 'fr',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'res-102',
    customer_name: 'Thomas Laurent',
    email: 'thomas.laurent@example.fr',
    phone: '+33 6 12 34 56 78',
    country: 'France',
    vehicle_id: 'veh-4',
    vehicle_name: 'Hyundai Tucson Automatique',
    location_id: 'loc-1',
    location_name: 'Laâyoune',
    pickup_date: '2026-10-08',
    return_date: '2026-10-15',
    message: 'Mission professionnelle à Laâyoune. 2ème conducteur gratuit souhaité.',
    status: 'confirmed',
    language: 'fr',
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
  {
    id: 'res-103',
    customer_name: 'Fatima Zahra El Alami',
    email: 'fz.alami@example.com',
    phone: '+212 662 987 654',
    country: 'Maroc',
    vehicle_id: 'veh-2',
    vehicle_name: 'Dacia Sandero Stepway',
    location_id: 'loc-2',
    location_name: 'Boujdour',
    pickup_date: '2026-10-10',
    return_date: '2026-10-14',
    message: 'Prise en charge au centre-ville de Boujdour.',
    status: 'contacted',
    language: 'ar',
    created_at: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Mehdi R.',
    rating: 5,
    content_fr: 'Service irréprochable à Laâyoune. Voiture Duster 4x4 très propre, livrée à l’heure à l’aéroport. Kilométrage illimité respecté sans mauvaise surprise.',
    content_en: 'Flawless service in Laâyoune. The Duster 4x4 was immaculate and delivered on time to the airport. Unlimited mileage honored with total transparency.',
    content_ar: 'خدمة لا غبار عليها في العيون. السيارة كانت نظيفة جدا واستلمتها في الوقت بالمطار. الكيلومترات غير محدودة ومعاملة احترافية.',
    published: true,
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'test-2',
    name: 'Sophie & Marc D.',
    rating: 5,
    content_fr: 'Séjour kite à Dakhla réussi grâce à SOUBAICAR. Récupération directe à l’arrivée de notre vol et assistance WhatsApp très réactive.',
    content_en: 'Successful kitesurf stay in Dakhla thanks to SOUBAICAR. Direct car pickup at the airport upon arrival and very responsive WhatsApp support.',
    content_ar: 'رحلة ممتازة إلى الداخلة بفضل سوبيكار. استلام مباشر للسيارة فور وصول الرحلة وتواصل سريع عبر واتساب.',
    published: true,
    created_at: '2026-08-28T14:30:00Z',
  },
  {
    id: 'test-3',
    name: 'Omar K.',
    rating: 5,
    content_fr: 'Client régulier entre Boujdour et Laâyoune pour mes déplacements d’affaires. Véhicules bien entretenus et contrat clair.',
    content_en: 'Regular business customer traveling between Boujdour and Laâyoune. Well-maintained cars and clear straightforward terms.',
    content_ar: 'زبون دائم للتنقل المهني بين بوجدور والعيون. سيارات بحالة ممتازة وعقود واضحة واحترافية عالية.',
    published: true,
    created_at: '2026-09-02T09:15:00Z',
  },
];

export const INITIAL_CORPORATE_QUOTE_REQUESTS: CorporateQuoteRequest[] = [];

export const INITIAL_SETTINGS: SiteSettings = {
  company_name: 'SOUBAICAR',
  email: 'contact@soubaicar.ma',
  phone: '+212 661 140 000',
  whatsapp: '+212 661 140 000',
  social_facebook: 'https://facebook.com/soubaicar',
  social_instagram: 'https://instagram.com/soubaicar',
  default_language: 'fr',
  hero_title_fr: 'Location de voitures à Laâyoune, Boujdour et Dakhla',
  hero_title_en: 'Car Rental in Laâyoune, Boujdour, and Dakhla',
  hero_title_ar: 'كراء السيارات في العيون، بوجدور والداخلة',
  hero_subtitle_fr: 'Une flotte fiable et adaptée à vos déplacements professionnels, personnels et touristiques dans le Sud du Maroc.',
  hero_subtitle_en: 'A reliable fleet tailored to your business, personal, and tourism travel across Southern Morocco.',
  hero_subtitle_ar: 'أسطول موثوق وملائم لتنقلاتكم المهنية والشخصية والسياحية في جنوب المملكة المغربية.',
  footer_text_fr: 'SOUBAICAR - Votre partenaire de confiance pour la location de véhicules dans les provinces du Sud : Laâyoune, Boujdour et Dakhla.',
  footer_text_en: 'SOUBAICAR - Your trusted car rental partner across the Southern provinces: Laâyoune, Boujdour, and Dakhla.',
  footer_text_ar: 'سوبيكار - شريككم الموثوق لكراء السيارات في الأقاليم الجنوبية: العيون، بوجدور والداخلة.',
};
