import type { LocationItem, Vehicle, Testimonial, SiteSettings, Reservation, CorporateQuoteRequest, ContactMessage } from '../types/database';

import heroImg from '../assets/images/hero_soubaicar_morocco_1790271578816.jpg';
import agencyLaayouneImg from '../assets/images/agency_laayoune_facade_1790271591267.jpg';
import agencyDakhlaImg from '../assets/images/agency_dakhla_lagoon_1790271602448.jpg';
import agencyBoujdourImg from '../assets/images/agency_boujdour_coast_1790271613020.jpg';
import vehicleSuvImg from '../assets/images/vehicle_suv_showcase_1790271623037.jpg';

export const ASSET_IMAGES = {
  hero: heroImg,
  agencyLaayoune: agencyLaayouneImg,
  agencyDakhla: agencyDakhlaImg,
  agencyBoujdour: agencyBoujdourImg,
  vehicleSuv: vehicleSuvImg,
};

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'loc-1',
    name: 'Laâyoune',
    slug: 'laayoune',
    address: 'Boulevard Mekka / Avenue de l’Islam, Laâyoune 70000, Maroc',
    phone: '+212 661 384 118',
    whatsapp: '+212 662 104 425',
    email: 'Contact@soubaicar.com',
    map_url: 'https://www.google.com/maps?ll=27.149924,-13.200756&z=15&t=m&hl=fr&gl=US&mapclient=embed&cid=2200714300719536469',
    description_fr: 'Agence principale SOUBAICAR à Laâyoune. Mise à disposition rapide en ville et livraison immédiate à l’Aéroport Laâyoune Hassan 1er.',
    description_en: 'Main SOUBAICAR branch in Laâyoune. Fast city pickup and express delivery to Laâyoune Hassan 1st International Airport.',
    description_ar: 'وكالة سوبيكار الرئيسية في العيون. تسليم فوري داخل المدينة وفي مطار العيون الحسن الأول.',
    image_url: agencyLaayouneImg,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'loc-2',
    name: 'Boujdour',
    slug: 'boujdour',
    address: 'Boulevard Hassan II, Centre-Ville, Boujdour 71000, Maroc',
    phone: '+212 662 104 425',
    whatsapp: '+212 662 104 425',
    email: 'Contact@soubaicar.com',
    description_fr: 'Agence SOUBAICAR Boujdour. Service de proximité pour vos trajets professionnels et voyages le long de la côte atlantique.',
    description_en: 'SOUBAICAR Boujdour branch. Reliable local service for business trips and coastal travel along the Atlantic corridor.',
    description_ar: 'وكالة سوبيكار في بوجدور. خدمة متميزة لرحلاتكم المهنية والشخصية على طول الساحل الأطلسي.',
    image_url: agencyBoujdourImg,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'loc-3',
    name: 'Dakhla',
    slug: 'dakhla',
    address: 'Boulevard Mohammed V & Accueil Aéroport Dakhla, Dakhla 73000, Maroc',
    phone: '+212 662 104 479',
    whatsapp: '+212 662 104 425',
    email: 'Contact@soubaicar.com',
    description_fr: 'Agence SOUBAICAR Dakhla. Flotte adaptée pour la lagune, les spots de kitesurf, le désert et livraison directe à l’Aéroport de Dakhla.',
    description_en: 'SOUBAICAR Dakhla branch. Premium vehicles tailored for lagoon exploration, desert excursions, and direct Dakhla Airport delivery.',
    description_ar: 'وكالة سوبيكار في الداخلة. أسطول مناسب للبحيرة، مناطق الرياضات البحرية، الصحراء مع التوصيل لمطار الداخلة.',
    image_url: agencyDakhlaImg,
    active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    name: 'Dacia Dokker',
    slug: 'dacia-dokker',
    category: 'Utilitaire',
    fuel: 'Diesel',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: null,
    description_fr: 'Utilitaire pratique et spacieux, idéal pour les déplacements professionnels, le transport de matériel et les missions locales à Laâyoune, Boujdour et Dakhla.',
    description_en: 'Practical and spacious utility vehicle suited for business travel, equipment transport and local operations across Southern Morocco.',
    description_ar: 'سيارة عملية ومتسعة مناسبة للسفر المهني ونقل المعدات والمهام المحلية في العيون وبوجدور والداخلة.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-2',
    name: 'Dacia Duster',
    slug: 'dacia-duster',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: null,
    description_fr: 'SUV robuste et économique, parfait pour les routes du Sud et les randonnées en extérieur sans compromis sur le confort.',
    description_en: 'Robust and economical SUV, ideal for Southern Morocco roads and outdoor trips with comfort preserved.',
    description_ar: 'سيارة دفع رباعي قوية واقتصادية مثالية للطرق الجنوبية والرحلات الخارجية مع الراحة المطلوبة.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-3',
    name: 'Volkswagen Touareg',
    slug: 'volkswagen-touareg',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Automatique',
    seats: 5,
    air_conditioning: true,
    price: null,
    description_fr: 'SUV haut de gamme avec un vrai confort premium, parfait pour les déplacements professionnels et les trajets longue distance.',
    description_en: 'Premium SUV delivering strong comfort and capability for long-distance and professional travel across the region.',
    description_ar: 'سيارة دفع رباعي فاخرة توفر راحة كبيرة وقدرة ممتازة للرحلات الطويلة والتنقلات المهنية.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-4',
    name: 'Hyundai Accent',
    slug: 'hyundai-accent',
    category: 'Citadine',
    fuel: 'Essence',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: null,
    description_fr: 'Citadine fiable, économique et très pratique pour la ville, les courts séjours et les déplacements quotidiens.',
    description_en: 'Reliable, economical city car designed for daily use, short stays and urban commuting in comfort.',
    description_ar: 'سيارة مدينة موثوقة واقتصادية ومريحة للتنقل اليومي والرحلات القصيرة في المدينة.',
    image_url: vehicleSuvImg,
    featured: false,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-5',
    name: 'Dacia Logan',
    slug: 'dacia-logan',
    category: 'Berline',
    fuel: 'Diesel',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: null,
    description_fr: 'Berline abordable, confortable et simple à conduire, adaptée aux déplacements urbains et régionaux.',
    description_en: 'Affordable, comfortable sedan built for city and regional travel with everyday practicality.',
    description_ar: 'سيارة عائلية اقتصادية ومريحة ومناسبة للتنقل داخل المدينة وبين المدن.',
    image_url: vehicleSuvImg,
    featured: false,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-6',
    name: '4x4 Mitsubishi Pick Up',
    slug: '4x4-mitsubishi-pick-up',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Manuelle',
    seats: 5,
    air_conditioning: true,
    price: null,
    description_fr: 'Pick-up 4x4 robuste, très apprécié pour les missions terrain, le transport de matériel et les déplacements en zone aride.',
    description_en: 'Robust 4x4 pickup suited for rough terrain, material transport and desert-region missions.',
    description_ar: 'بيك أب قوي برفع رباعي مناسب للمشاريع الميدانية ونقل المعدات في المناطق الصحراوية.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-7',
    name: 'Hyundai Tucson',
    slug: 'hyundai-tucson',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Automatique',
    seats: 5,
    air_conditioning: true,
    price: null,
    description_fr: 'SUV confortable et fiable pour les longs trajets, les familles et les déplacements professionnels dans le Sud.',
    description_en: 'Comfortable and reliable SUV for long drives, family travel and business mobility across Southern Morocco.',
    description_ar: 'سيارة دفع رباعي مريحة وموثوقة للرحلات الطويلة والتنقلات العائلية والمهنية.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-8',
    name: '4x4 Skoda Kodiaq',
    slug: '4x4-skoda-kodiaq',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Automatique',
    seats: 7,
    air_conditioning: true,
    price: null,
    description_fr: 'SUV 7 places spacieux et robuste, idéal pour les familles, les déplacements d’équipe et les zones rurales difficiles.',
    description_en: 'Spacious 7-seat SUV built for families, team travel and rougher roads across the South.',
    description_ar: 'سيارة دفع رباعي واسعة بـ7 مقاعد مناسبة للعائلات وتنقلات الفرق والطرق الوعرة.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-9',
    name: 'Nissan Qashqai',
    slug: 'nissan-qashqai',
    category: 'SUV',
    fuel: 'Essence',
    transmission: 'Automatique',
    seats: 5,
    air_conditioning: true,
    price: null,
    description_fr: 'SUV compact élégant au bon rapport confort / polyvalence pour les trajets quotidiens et les week-ends.',
    description_en: 'Elegant compact SUV with excellent versatility and comfort for everyday outings and weekend travel.',
    description_ar: 'سيارة SUV صغيرة أنيقة ومتعددة الاستخدامات للرحلات اليومية وفي عطلات نهاية الأسبوع.',
    image_url: vehicleSuvImg,
    featured: false,
    available: true,
    location_ids: ['loc-1', 'loc-2', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-10',
    name: '4x4 Pajero Sport',
    slug: '4x4-pajero-sport',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Automatique',
    seats: 7,
    air_conditioning: true,
    price: null,
    description_fr: 'SUV 4x4 et très spacieux, conçu pour les missions difficiles, les déplacements familiaux et les randonnées en terrain accidenté.',
    description_en: 'Versatile 4x4 SUV with ample space for demanding missions, large families and rough-road travel.',
    description_ar: 'SUV قوي ومريح مع مساحة كبيرة للمهام الصعبة والتنقل العائلي والطرق الوعرة.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'veh-11',
    name: '4x4 Toyota Fortuner',
    slug: '4x4-toyota-fortuner',
    category: 'SUV & 4x4',
    fuel: 'Diesel',
    transmission: 'Automatique',
    seats: 7,
    air_conditioning: true,
    price: null,
    description_fr: '4x4 fiable et puissant, parfait pour les trajets entre villes, les déplacements d’équipe et les routes désertiques.',
    description_en: 'Reliable and capable 4x4 vehicle designed for intercity travel, team assignments and desert routes.',
    description_ar: 'سيارة 4x4 موثوقة وقوية مناسبة للرحلات بين المدن والتنقلات الجماعية والطرق الصحراوية.',
    image_url: vehicleSuvImg,
    featured: true,
    available: true,
    location_ids: ['loc-1', 'loc-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-101',
    customer_name: 'Karim Bennani',
    email: 'karim.bennani@example.com',
    phone: '+212 661 234 567',
    country: 'Maroc',
    vehicle_id: 'veh-1',
    vehicle_name: 'Dacia Duster 4x4 Prestige',
    location_id: 'loc-3',
    location_name: 'Dakhla',
    pickup_date: '2026-10-05',
    return_date: '2026-10-12',
    message: 'Arrivée vol AT1422 à Dakhla à 14h30. Besoin de livraison à l’aéroport.',
    status: 'new',
    language: 'fr',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'res-102',
    customer_name: 'Thomas Laurent',
    email: 'thomas.laurent@example.fr',
    phone: '+33 6 12 34 56 78',
    country: 'France',
    vehicle_id: 'veh-4',
    vehicle_name: 'Hyundai Tucson Automatique',
    location_id: 'loc-1',
    location_name: 'Laâyoune',
    pickup_date: '2026-10-08',
    return_date: '2026-10-15',
    message: 'Mission professionnelle à Laâyoune. 2ème conducteur gratuit souhaité.',
    status: 'confirmed',
    language: 'fr',
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
  {
    id: 'res-103',
    customer_name: 'Fatima Zahra El Alami',
    email: 'fz.alami@example.com',
    phone: '+212 662 987 654',
    country: 'Maroc',
    vehicle_id: 'veh-2',
    vehicle_name: 'Dacia Sandero Stepway',
    location_id: 'loc-2',
    location_name: 'Boujdour',
    pickup_date: '2026-10-10',
    return_date: '2026-10-14',
    message: 'Prise en charge au centre-ville de Boujdour.',
    status: 'contacted',
    language: 'ar',
    created_at: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Mehdi R.',
    rating: 5,
    content_fr: 'Service irréprochable à Laâyoune. Voiture Duster 4x4 très propre, livrée à l’heure à l’aéroport. Kilométrage illimité respecté sans mauvaise surprise.',
    content_en: 'Flawless service in Laâyoune. The Duster 4x4 was immaculate and delivered on time to the airport. Unlimited mileage honored with total transparency.',
    content_ar: 'خدمة لا غبار عليها في العيون. السيارة كانت نظيفة جدا واستلمتها في الوقت بالمطار. الكيلومترات غير محدودة ومعاملة احترافية.',
    published: true,
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'test-2',
    name: 'Sophie & Marc D.',
    rating: 5,
    content_fr: 'Séjour kite à Dakhla réussi grâce à SOUBAICAR. Récupération directe à l’arrivée de notre vol et assistance WhatsApp très réactive.',
    content_en: 'Successful kitesurf stay in Dakhla thanks to SOUBAICAR. Direct car pickup at the airport upon arrival and very responsive WhatsApp support.',
    content_ar: 'رحلة ممتازة إلى الداخلة بفضل سوبيكار. استلام مباشر للسيارة فور وصول الرحلة وتواصل سريع عبر واتساب.',
    published: true,
    created_at: '2026-08-28T14:30:00Z',
  },
  {
    id: 'test-3',
    name: 'Omar K.',
    rating: 5,
    content_fr: 'Client régulier entre Boujdour et Laâyoune pour mes déplacements d’affaires. Véhicules bien entretenus et contrat clair.',
    content_en: 'Regular business customer traveling between Boujdour and Laâyoune. Well-maintained cars and clear straightforward terms.',
    content_ar: 'زبون دائم للتنقل المهني بين بوجدور والعيون. سيارات بحالة ممتازة وعقود واضحة واحترافية عالية.',
    published: true,
    created_at: '2026-09-02T09:15:00Z',
  },
];

export const INITIAL_CORPORATE_QUOTE_REQUESTS: CorporateQuoteRequest[] = [];

export const INITIAL_CONTACT_MESSAGES: ContactMessage[] = [];

export const INITIAL_SETTINGS: SiteSettings = {
  company_name: 'SOUBAICAR',
  email: 'Contact@soubaicar.com',
  phone: '+212 662 104 425',
  whatsapp: '+212 662 104 425',
  social_facebook: 'https://www.facebook.com/SOUBAICAR/',
  social_instagram: 'https://www.linkedin.com/company/location-de-voitures-soubai/',
  default_language: 'fr',
  hero_title_fr: 'Location de voitures à Laâyoune et Dakhla',
  hero_title_en: 'Car Rental in Laâyoune and Dakhla',
  hero_title_ar: 'كراء السيارات في العيون والداخلة',
  hero_subtitle_fr: 'Une flotte fiable et adaptée à vos déplacements professionnels, personnels et touristiques dans le Sud du Maroc.',
  hero_subtitle_en: 'A reliable fleet tailored to your business, personal, and tourism travel across Southern Morocco.',
  hero_subtitle_ar: 'أسطول موثوق وملائم لتنقلاتكم المهنية والشخصية والسياحية في جنوب المملكة المغربية.',
  footer_text_fr: 'SOUBAICAR - Votre partenaire de confiance pour la location de véhicules dans les provinces du Sud : Laâyoune, Boujdour et Dakhla.',
  footer_text_en: 'SOUBAICAR - Your trusted car rental partner across the Southern provinces: Laâyoune, Boujdour, and Dakhla.',
  footer_text_ar: 'سوبيكار - شريككم الموثوق لكراء السيارات في الأقاليم الجنوبية: العيون، بوجدور والداخلة.',
};
